<?php

return [
    'launch_services' => [
        'تركيب فلاتر المياه بالرياض',
        'صيانة فلاتر المياه بالرياض',
        'تغيير شمعات فلاتر المياه بالرياض',
        'تركيب أجهزة تحلية المياه المنزلية بالرياض',
        'صيانة أجهزة تحلية المياه بالرياض',
        'تركيب محطات تحلية المياه بالرياض',
        'صيانة محطات تحلية المياه بالرياض',
        'تركيب فلتر جامبو للخزان بالرياض',
        'تركيب فلتر شاور بالرياض',
        'تركيب وصيانة أنظمة الضباب والرذاذ بالرياض',
    ],
    'service_taxonomy' => [
        'فلاتر المياه' => [
            'تركيب فلاتر المياه بالرياض',
            'تغيير شمعات فلاتر المياه بالرياض',
            'تركيب فلتر جامبو للخزان بالرياض',
            'تركيب فلتر شاور بالرياض',
        ],
        'أجهزة التحلية المنزلية' => [
            'تركيب أجهزة تحلية المياه المنزلية بالرياض',
            'صيانة أجهزة تحلية المياه بالرياض',
        ],
        'محطات التحلية' => [
            'تركيب محطات تحلية المياه بالرياض',
            'صيانة محطات تحلية المياه بالرياض',
        ],
        'الصيانة والضباب والرذاذ' => [
            'صيانة فلاتر المياه بالرياض',
            'تركيب وصيانة أنظمة الضباب والرذاذ بالرياض',
        ],
    ],
    'service_featured_images' => [
        'تركيب فلاتر المياه بالرياض' => 'services/water-filter-installation-riyadh.webp',
        'صيانة فلاتر المياه بالرياض' => 'services/water-filter-faucet.webp',
        'تغيير شمعات فلاتر المياه بالرياض' => 'services/water-filter-replacement-riyadh.webp',
        'تركيب أجهزة تحلية المياه المنزلية بالرياض' => 'services/seven-stage-home-water-purifier.webp',
        'صيانة أجهزة تحلية المياه بالرياض' => 'services/seven-stage-home-water-purifier2.webp',
        'تركيب محطات تحلية المياه بالرياض' => 'services/water-treatment-station-maintenance-riyadh.webp',
        'صيانة محطات تحلية المياه بالرياض' => 'services/three-stage-jumbo-water-filter.webp',
        'تركيب فلتر جامبو للخزان بالرياض' => 'services/three-stage-jumbo-water-filter.webp',
        'تركيب فلتر شاور بالرياض' => 'services/shower-water-filter.webp',
        'تركيب وصيانة أنظمة الضباب والرذاذ بالرياض' => 'services/mist-and-fog-system-installation-riyadh.webp',
    ],
    'article_featured_images' => [
        'أفضل فلتر مياه منزلي في الرياض: كيف تختار الجهاز المناسب؟' => 'services/water-filter-installation-riyadh.webp',
        'أسعار فلاتر المياه المنزلية مع التركيب في الرياض' => 'services/water-filter-replacement-riyadh.webp',
        'فلتر مياه 7 مراحل: المميزات والمراحل والسعر في الرياض' => 'services/seven-stage-home-water-purifier.webp',
        'فلتر جامبو 3 مراحل للخزان: المميزات والسعر والتركيب بالرياض' => 'services/three-stage-jumbo-water-filter.webp',
        'متى يجب تغيير شمعات فلتر المياه؟ دليل الصيانة في الرياض' => 'services/water-filter-faucet.webp',
        'الفرق بين فلتر تنقية المياه وجهاز تحلية المياه المنزلي' => 'services/seven-stage-home-water-purifier2.webp',
        'أفضل محطة تحلية مياه للمطاعم والكافيهات في الرياض' => 'services/water-treatment-station-maintenance-riyadh.webp',
        'محطة تحلية 400 جالون: المواصفات والاستخدام والسعر بالرياض' => 'services/water-treatment-station-maintenance-riyadh.webp',
        'أسباب ضعف ضغط الماء في فلتر التحلية وطريقة صيانته' => 'services/shower-water-filter2.webp',
        'أفضل شركة تركيب وصيانة فلاتر مياه بالرياض' => 'services/mist-and-fog-system-installation-riyadh.webp',
    ],
    'about_image' => 'services/seven-stage-home-water-purifier2.webp',
    'header_image' => 'services/water-filter-installation-riyadh.webp',
    'hero_image' => 'services/water-filter-installation-riyadh.webp',
    'fallback' => [
        'site_name' => 'فلاتر وتحلية المياه بالرياض',
        'phone_display' => '050 943 9667',
        'phone_e164' => '+966509439667',
        'phone_tel' => 'tel:+966509439667',
        'whatsapp_url' => 'https://wa.me/966509439667',
        'address' => 'الرياض، حي المونسية، المملكة العربية السعودية',
        'city' => 'الرياض',
        'country' => 'المملكة العربية السعودية',
        'locale' => 'ar_SA',
        'search_console_verification' => '',
        'ga_measurement_id' => '',
        'logo_url' => '',
    ],
];
